I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/init.rpy", line 13, in script
    init python:
  File "game/init.rpy", line 109, in <module>
    MapEmote('kamika d sigh' 'kamika pose1 base md mad happy ec default brow sad')
TypeError: MapEmote() takes at least 2 arguments (1 given)

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/init.rpy", line 13, in script
    init python:
  File "E:\renpy-6.99.12.4-sdk\renpy\ast.py", line 862, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "E:\renpy-6.99.12.4-sdk\renpy\python.py", line 1912, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/init.rpy", line 109, in <module>
    MapEmote('kamika d sigh' 'kamika pose1 base md mad happy ec default brow sad')
TypeError: MapEmote() takes at least 2 arguments (1 given)

Windows-8-6.2.9200
Ren'Py 7.0.0.196
 
Wed Nov 07 03:04:09 2018
