I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/init.rpy", line 17, in script
    init python:
  File "game/init.rpy", line 18, in <module>
    DefineImages('bgs', prepend='bg')
NameError: name 'DefineImages' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/init.rpy", line 17, in script
    init python:
  File "E:\renpy-6.99.12.4-sdk\renpy\ast.py", line 862, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "E:\renpy-6.99.12.4-sdk\renpy\python.py", line 1912, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/init.rpy", line 18, in <module>
    DefineImages('bgs', prepend='bg')
NameError: name 'DefineImages' is not defined

Windows-8-6.2.9200
Ren'Py 7.0.0.196
 
Wed Oct 31 23:38:14 2018
